// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY7O2N4WVKO7lIAABXHw6D0INPjO1aDTg',
    appId: '1:903048075075:web:dedd0dbd5aaa8bfe9a81f6',
    messagingSenderId: '903048075075',
    projectId: 'congressional-app-challe-983a5',
    authDomain: 'congressional-app-challe-983a5.firebaseapp.com',
    storageBucket: 'congressional-app-challe-983a5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWlT-UheeiDejC9PPaEwEhMCGfebjurTU',
    appId: '1:903048075075:android:909983c7c52753589a81f6',
    messagingSenderId: '903048075075',
    projectId: 'congressional-app-challe-983a5',
    storageBucket: 'congressional-app-challe-983a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3e-tXB1vwbJZCCSvhOE0UKulOYXe2-cE',
    appId: '1:903048075075:ios:1bf59689cfeef7a19a81f6',
    messagingSenderId: '903048075075',
    projectId: 'congressional-app-challe-983a5',
    storageBucket: 'congressional-app-challe-983a5.firebasestorage.app',
    iosBundleId: 'com.example.firstFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3e-tXB1vwbJZCCSvhOE0UKulOYXe2-cE',
    appId: '1:903048075075:ios:1bf59689cfeef7a19a81f6',
    messagingSenderId: '903048075075',
    projectId: 'congressional-app-challe-983a5',
    storageBucket: 'congressional-app-challe-983a5.firebasestorage.app',
    iosBundleId: 'com.example.firstFlutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY7O2N4WVKO7lIAABXHw6D0INPjO1aDTg',
    appId: '1:903048075075:web:0f632ff5b54110e49a81f6',
    messagingSenderId: '903048075075',
    projectId: 'congressional-app-challe-983a5',
    authDomain: 'congressional-app-challe-983a5.firebaseapp.com',
    storageBucket: 'congressional-app-challe-983a5.firebasestorage.app',
  );
}
